/**
 * ============================================================================
 * Workspace Mock Data
 * ----------------------------------------------------------------------------
 * Provides temporary workspace data until backend integration is available.
 * ============================================================================
 */

import type { WorkspaceItem } from "./workspace.types";

/**
 * ============================================================================
 * Mock Items
 * ============================================================================
 */

export const workspaceItemsMock: WorkspaceItem[] = [
    {
        id: "folder-001",
        projectId: "project-001",
        ltrDescription: "Main folder for project documents",
        type: "folder",
        name: "اسناد پروژه",
        description: "پوشه اصلی اسناد پروژه",
        updatedAt: "2026-07-17T08:00:00.000Z",
        status: "active",
        parentFolderId: null,
        childrenCount: 3,
    },
    {
        id: "folder-002",
        projectId: "project-002",
        ltrDescription: "Approved and signed contracts",
        type: "folder",
        name: "قراردادها",
        description: "مجموعه قراردادهای تأیید و امضا شده",
        updatedAt: "2026-07-16T12:20:00.000Z",
        status: "active",
        parentFolderId: null,
        childrenCount: 2,
    },
    {
        id: "folder-003",
        projectId: "project-003",
        ltrDescription: "Project financial reports and records",
        type: "folder",
        name: "گزارش‌های مالی",
        description: "گزارش‌ها و مستندات مالی پروژه",
        updatedAt: "2026-07-15T09:45:00.000Z",
        status: "active",
        parentFolderId: null,
        childrenCount: 2,
    },
    {
        id: "file-001",
        projectId: "project-002",
        ltrDescription: "Approved main contract file",
        type: "file",
        name: "قرارداد اصلی",
        description: "فایل قرارداد تأیید شده",
        updatedAt: "2026-07-17T14:30:00.000Z",
        status: "active",
        parentFolderId: "folder-002",
        extension: "pdf",
        sizeBytes: 2.4 * 1024 * 1024,
        sizeLabel: "۲.۴ مگابایت",
    },
    {
        id: "file-002",
        projectId: "project-001",
        ltrDescription: "Final document handover minutes",
        type: "file",
        name: "صورتجلسه تحویل",
        description: "صورتجلسه نهایی تحویل مدارک",
        updatedAt: "2026-07-16T16:10:00.000Z",
        status: "active",
        parentFolderId: "folder-001",
        extension: "docx",
        sizeBytes: 780 * 1024,
        sizeLabel: "۷۸۰ کیلوبایت",
    },
    {
        id: "file-003",
        projectId: "project-001",
        ltrDescription: "Project execution schedule",
        type: "file",
        name: "برنامه زمان‌بندی",
        description: "فایل زمان‌بندی اجرای پروژه",
        updatedAt: "2026-07-15T18:25:00.000Z",
        status: "active",
        parentFolderId: "folder-001",
        extension: "xlsx",
        sizeBytes: 1.1 * 1024 * 1024,
        sizeLabel: "۱.۱ مگابایت",
    },
    {
        id: "file-004",
        projectId: "project-003",
        ltrDescription: "July payment and financial status report",
        type: "file",
        name: "گزارش پرداخت تیر",
        description: "گزارش پرداخت و وضعیت مالی تیرماه",
        updatedAt: "2026-07-14T11:00:00.000Z",
        status: "active",
        parentFolderId: "folder-003",
        extension: "pdf",
        sizeBytes: 1.8 * 1024 * 1024,
        sizeLabel: "۱.۸ مگابایت",
    },
    {
        id: "file-005",
        projectId: "project-002",
        ltrDescription: "Technical appendix for the main contract",
        type: "file",
        name: "پیوست فنی قرارداد",
        description: "پیوست فنی مرتبط با قرارداد اصلی",
        updatedAt: "2026-07-13T10:15:00.000Z",
        status: "active",
        parentFolderId: "folder-002",
        extension: "pdf",
        sizeBytes: 3.2 * 1024 * 1024,
        sizeLabel: "۳.۲ مگابایت",
    },
    {
        id: "file-006",
        projectId: "project-001",
        ltrDescription: "Initial proposed project budget",
        type: "file",
        name: "بودجه پیشنهادی",
        description: "نسخه اولیه بودجه پیشنهادی پروژه",
        updatedAt: "2026-07-12T13:40:00.000Z",
        status: "archived",
        parentFolderId: null,
        extension: "xlsx",
        sizeBytes: 950 * 1024,
        sizeLabel: "۹۵۰ کیلوبایت",
    },
    {
        id: "file-007",
        projectId: "project-002",
        ltrDescription: "Superseded contract version",
        type: "file",
        name: "نسخه قدیمی قرارداد",
        description: "نسخه قبلی قرارداد که دیگر استفاده نمی‌شود",
        updatedAt: "2026-07-11T08:30:00.000Z",
        status: "trashed",
        parentFolderId: null,
        extension: "pdf",
        sizeBytes: 2.1 * 1024 * 1024,
        sizeLabel: "۲.۱ مگابایت",
    },
];
