import {
    AlignRight,
    Archive,
    ArrowLeft,
    ArrowRight,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    ChevronUp,
    Check,
    Circle,
    Cloud,
    CloudCog,
    CloudOff,
    Download,
    Ellipsis,
    ExternalLink,
    File,
    FileText,
    Filter,
    Folder,
    FolderPlus,
    Grid3X3,
    Image,
    List,
    LogOut,
    Maximize2,
    Menu,
    PanelLeftClose,
    PanelLeftOpen,
    PanelRightClose,
    PanelRightOpen,
    Pin,
    RotateCcw,
    Search,
    Settings,
    Trash2,
    UploadCloud,
    User,
    Users,
    X,
} from "lucide-react";
import type { CSSProperties } from "react";

const icons: Record<string, React.ComponentType<any>> = {
    "align-right": AlignRight,
    archive: Archive,
    "arrow-left": ArrowLeft,
    "arrow-right": ArrowRight,
    "chevron-left": ChevronLeft,
    "chevron-right": ChevronRight,
    "chevron-down": ChevronDown,
    "chevron-up": ChevronUp,
    check: Check,
    cloud: Cloud,
    "cloud-cog": CloudCog,
    "cloud-off": CloudOff,
    download: Download,
    "external-link": ExternalLink,
    file: File,
    "file-text": FileText,
    filter: Filter,
    folder: Folder,
    "folder-plus": FolderPlus,
    grid: Grid3X3,
    image: Image,
    list: List,
    "log-out": LogOut,
    "maximize-2": Maximize2,
    menu: Menu,
    "panel-left-close": PanelLeftClose,
    "panel-left-open": PanelLeftOpen,
    "panel-right-close": PanelRightClose,
    "panel-right-open": PanelRightOpen,
    pin: Pin,
    "rotate-ccw": RotateCcw,
    search: Search,
    "more-horizontal": Ellipsis,
    settings: Settings,
    "trash-2": Trash2,
    "upload-cloud": UploadCloud,
    user: User,
    users: Users,
    x: X,
};

function FeatherIcon({ name, size = 24, color = "currentColor", style }: { name: string; size?: number; color?: string; style?: CSSProperties }) {
    const Icon = icons[name] ?? Circle;
    return <Icon aria-hidden="true" size={size} color={color} style={style} strokeWidth={1.8} />;
}

export const Feather = Object.assign(FeatherIcon, { glyphMap: {} as Record<string, number> });
